# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_ai.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1257, 904)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_30.setProperty("contentsMargins", QtCore.QRect(16, 16, 16, 16))
        self.verticalLayout_30.setSpacing(12)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setMinimumSize(QtCore.QSize(52, 80))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_30.addWidget(self.label_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_9 = QtWidgets.QGroupBox(Form)
        self.groupBox_9.setMinimumSize(QtCore.QSize(200, 100))
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_22.setProperty("contentsMargins", QtCore.QRect(16, 16, 16, 16))
        self.verticalLayout_22.setSpacing(10)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_22.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_22.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_22.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_22.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.page_8)
        self.vboxlayout.setProperty("contentsMargins", QtCore.QRect(0, 0, 0, 0))
        self.vboxlayout.setSpacing(12)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupBox_10 = QtWidgets.QGroupBox(self.page_8)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_6.setProperty("contentsMargins", QtCore.QRect(16, 16, 16, 16))
        self.horizontalLayout_6.setSpacing(16)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSpacing(10)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_3 = QtWidgets.QLabel(self.groupBox_10)
        self.label_3.setMinimumSize(QtCore.QSize(360, 280))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/liu/Pictures/F7A1EDA62C651FF02CC757D404774CC6.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_23.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox_10)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_23.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout_23.addLayout(self.horizontalLayout_4)
        self.label = QtWidgets.QLabel(self.groupBox_10)
        self.label.setObjectName("label")
        self.verticalLayout_23.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_23.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_23)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_10)
        self.frame_5.setMinimumSize(QtCore.QSize(320, 0))
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_29.setProperty("contentsMargins", QtCore.QRect(20, 20, 20, 20))
        self.verticalLayout_29.setSpacing(12)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_29.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setMinimumSize(QtCore.QSize(120, 120))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("C:/Users/liu/Pictures/F7A1EDA62C651FF02CC757D404774CC6.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_29.addWidget(self.label_8)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setHorizontalSpacing(16)
        self.formLayout_2.setVerticalSpacing(12)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.verticalLayout_29.addLayout(self.formLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_7.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_7.addWidget(self.radioButton)
        self.verticalLayout_29.addLayout(self.horizontalLayout_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_29.addWidget(self.pushButton_9)
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.vboxlayout.addWidget(self.groupBox_10)
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.page_9)
        self.vboxlayout1.setProperty("contentsMargins", QtCore.QRect(0, 0, 0, 0))
        self.vboxlayout1.setSpacing(12)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.groupBox_11 = QtWidgets.QGroupBox(self.page_9)
        self.groupBox_11.setObjectName("groupBox_11")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.hboxlayout.setProperty("contentsMargins", QtCore.QRect(16, 16, 16, 16))
        self.hboxlayout.setSpacing(16)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout2 = QtWidgets.QVBoxLayout()
        self.vboxlayout2.setSpacing(10)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_11)
        self.label_11.setMinimumSize(QtCore.QSize(360, 280))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("C:/Users/liu/Pictures/F7A1EDA62C651FF02CC757D404774CC6.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.vboxlayout2.addWidget(self.label_11)
        self.label_51 = QtWidgets.QLabel(self.groupBox_11)
        self.label_51.setObjectName("label_51")
        self.vboxlayout2.addWidget(self.label_51)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_39.setObjectName("pushButton_39")
        self.hboxlayout1.addWidget(self.pushButton_39)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.hboxlayout1.addWidget(self.lineEdit_24)
        self.vboxlayout2.addLayout(self.hboxlayout1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_11)
        self.label_52.setObjectName("label_52")
        self.vboxlayout2.addWidget(self.label_52)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_40.setObjectName("pushButton_40")
        self.hboxlayout2.addWidget(self.pushButton_40)
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_41.setObjectName("pushButton_41")
        self.hboxlayout2.addWidget(self.pushButton_41)
        self.vboxlayout2.addLayout(self.hboxlayout2)
        self.hboxlayout.addLayout(self.vboxlayout2)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_11)
        self.frame_6.setMinimumSize(QtCore.QSize(320, 0))
        self.frame_6.setObjectName("frame_6")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.vboxlayout3.setProperty("contentsMargins", QtCore.QRect(20, 20, 20, 20))
        self.vboxlayout3.setSpacing(12)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        self.label_28.setMinimumSize(QtCore.QSize(50, 40))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.vboxlayout3.addWidget(self.label_28)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.frame_6)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.vboxlayout3.addWidget(self.plainTextEdit_4)
        self.hboxlayout.addWidget(self.frame_6)
        self.vboxlayout1.addWidget(self.groupBox_11)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.vboxlayout4 = QtWidgets.QVBoxLayout(self.page_10)
        self.vboxlayout4.setProperty("contentsMargins", QtCore.QRect(0, 0, 0, 0))
        self.vboxlayout4.setSpacing(12)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.groupBox_12 = QtWidgets.QGroupBox(self.page_10)
        self.groupBox_12.setObjectName("groupBox_12")
        self.vboxlayout5 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.vboxlayout5.setProperty("contentsMargins", QtCore.QRect(16, 16, 16, 16))
        self.vboxlayout5.setSpacing(12)
        self.vboxlayout5.setObjectName("vboxlayout5")
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setSpacing(8)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.hboxlayout3.addWidget(self.lineEdit_25)
        self.pushButton_42 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_42.setObjectName("pushButton_42")
        self.hboxlayout3.addWidget(self.pushButton_42)
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_43.setObjectName("pushButton_43")
        self.hboxlayout3.addWidget(self.pushButton_43)
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_44.setObjectName("pushButton_44")
        self.hboxlayout3.addWidget(self.pushButton_44)
        self.vboxlayout5.addLayout(self.hboxlayout3)
        self.tableView = QtWidgets.QTableView(self.groupBox_12)
        self.tableView.setObjectName("tableView")
        self.vboxlayout5.addWidget(self.tableView)
        self.vboxlayout4.addWidget(self.groupBox_12)
        self.stackedWidget.addWidget(self.page_10)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_30.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "人脸识别系统"))
        Form.setStyleSheet(_translate("Form", "\n"
"/* 主窗口 */\n"
"QWidget#Form {\n"
"    background-color: #f8f9fa;\n"
"}\n"
"\n"
"/* 标题 */\n"
"QLabel#label_10 {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"/* 普通文字 */\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"/* 分组框 */\n"
"QGroupBox {\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    border: 1px solid #dce6f0;\n"
"    border-radius: 10px;\n"
"    margin-top: 12px;\n"
"    background-color: #ffffff;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 8px;\n"
"    padding: 0 8px;\n"
"}\n"
"\n"
"/* 按钮 */\n"
"QPushButton {\n"
"    background-color: #409eff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #66b1ff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #337ecc;\n"
"}\n"
"\n"
"/* 输入框 */\n"
"QLineEdit, QPlainTextEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 6px;\n"
"    padding: 6px 8px;\n"
"    font-size: 14px;\n"
"    color: #2c3e50;\n"
"}\n"
"QLineEdit:focus, QPlainTextEdit:focus {\n"
"    border: 1px solid #409eff;\n"
"}\n"
"\n"
"/* 单选框 */\n"
"QRadioButton {\n"
"    font-size: 14px;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"/* 表格 */\n"
"QTableView {\n"
"    background-color: white;\n"
"    border: 1px solid #dce6f0;\n"
"    border-radius: 8px;\n"
"    gridline-color: #e4e7ed;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #e8f3ff;\n"
"    color: #2c3e50;\n"
"    border: none;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"/* 图片展示框 */\n"
"QLabel#label_3, QLabel#label_8, QLabel#label_11 {\n"
"    background-color: #ffffff;\n"
"    border: 1px dashed #c0c4cc;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* 面板 */\n"
"QFrame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e4e7ed;\n"
"    border-radius: 10px;\n"
"}\n"
"   "))
        self.label_10.setText(_translate("Form", "人脸识别系统"))
        self.groupBox_9.setTitle(_translate("Form", "功能选项"))
        self.pushButton_4.setText(_translate("Form", "人脸录入"))
        self.pushButton_3.setText(_translate("Form", "人脸识别"))
        self.pushButton_2.setText(_translate("Form", "数据库管理"))
        self.pushButton.setText(_translate("Form", "退出"))
        self.groupBox_10.setTitle(_translate("Form", "人脸信息录入"))
        self.label_2.setText(_translate("Form", "方式一：图片"))
        self.pushButton_5.setText(_translate("Form", "上传图片"))
        self.label.setText(_translate("Form", "方式二：摄像头"))
        self.pushButton_8.setText(_translate("Form", "拍照"))
        self.pushButton_6.setText(_translate("Form", "开启摄像头"))
        self.pushButton_7.setText(_translate("Form", "关闭摄像头"))
        self.label_9.setText(_translate("Form", "人脸信息"))
        self.label_4.setText(_translate("Form", "姓名"))
        self.label_6.setText(_translate("Form", "年龄"))
        self.label_5.setText(_translate("Form", "学号"))
        self.label_7.setText(_translate("Form", "性别"))
        self.radioButton_2.setText(_translate("Form", "男"))
        self.radioButton.setText(_translate("Form", "女"))
        self.pushButton_9.setText(_translate("Form", "保存信息"))
        self.groupBox_11.setTitle(_translate("Form", "人脸识别"))
        self.label_51.setText(_translate("Form", "方式一：图片"))
        self.pushButton_39.setText(_translate("Form", "上传图片"))
        self.label_52.setText(_translate("Form", "方式二：摄像头"))
        self.pushButton_40.setText(_translate("Form", "开启摄像头"))
        self.pushButton_41.setText(_translate("Form", "关闭摄像头"))
        self.label_28.setText(_translate("Form", "识别结果"))
        self.groupBox_12.setTitle(_translate("Form", "数据库管理"))
        self.lineEdit_25.setPlaceholderText(_translate("Form", "输入姓名/学号查询"))
        self.pushButton_42.setText(_translate("Form", "查询"))
        self.pushButton_43.setText(_translate("Form", "刷新"))
        self.pushButton_44.setText(_translate("Form", "删除"))
